name: linux

on:
  push:
  pull_request:

jobs:
  build-test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-x86_64-py313
            runner: ubuntu-24.04
            env_file: conda/environments/dev-linux_os-linux_arch-x86_64_py-313_cuda-none_compiler-llvm.yaml
            env_name: dev-linux_os-linux_arch-x86_64_py-313_cuda-none_compiler-llvm
            build_preset: ninja-multi
            build_dir: build
          - name: linux-x86_64-py314
            runner: ubuntu-24.04
            env_file: conda/environments/dev-linux_os-linux_arch-x86_64_py-314_cuda-none_compiler-llvm.yaml
            env_name: dev-linux_os-linux_arch-x86_64_py-314_cuda-none_compiler-llvm
            build_preset: ninja-multi
            build_dir: build
          - name: linux-arm64-py313
            runner: ubuntu-24.04-arm
            env_file: conda/environments/dev-linux-arm64_os-linux_arch-aarch64_py-313_cuda-none_compiler-llvm.yaml
            env_name: dev-linux-arm64_os-linux_arch-aarch64_py-313_cuda-none_compiler-llvm
            build_preset: ninja-multi
            build_dir: build
          - name: linux-arm64-py314
            runner: ubuntu-24.04-arm
            env_file: conda/environments/dev-linux-arm64_os-linux_arch-aarch64_py-314_cuda-none_compiler-llvm.yaml
            env_name: dev-linux-arm64_os-linux_arch-aarch64_py-314_cuda-none_compiler-llvm
            build_preset: ninja-multi
            build_dir: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: "1.5.10"
          environment-file: ${{ matrix.env_file }}
          environment-name: ${{ matrix.env_name }}
          cache-environment: true
          cache-environment-key: ${{ matrix.name }}

      - name: Configure
        shell: bash -l {0}
        run: |
          micromamba run -n "${{ matrix.env_name }}" cmake --preset "${{ matrix.build_preset }}"

      - name: Build (Release)
        shell: bash -l {0}
        run: |
          micromamba run -n "${{ matrix.env_name }}" cmake --build "${{ matrix.build_dir }}" --config Release --parallel

      - name: Test (Release)
        shell: bash -l {0}
        run: |
          micromamba run -n "${{ matrix.env_name }}" ctest --test-dir "${{ matrix.build_dir }}" --output-on-failure -C Release --timeout 300
